### ISSUE TITLE
Compiler Error C2888 on Visual Studio (15.8.9)

### ISSUE THREAD

**Issue by WolfgangVogl** [octobanana/belle#1]
Good morning,
I've tried to compile your library (the first, very very simple example for a http server that just echos back the request body) using microsoft visual studio (v15.8.9) and there a a lot of C2888 errors:

1>  c:\dev\packages\.conan\data\belle\0.9.0\auto\stable\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\belle\include\belle.hh(1201): error C2888: 'void <lambda_59fc3b57f109080765fee6635e6fcd48>::operator ()(_T1,_T2 &&) const': symbol cannot be defined within namespace 'Belle'
1>  c:\dev\packages\.conan\data\belle\0.9.0\auto\stable\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\belle\include\belle.hh(1216): error C2888: 'void <lambda_59fc3b57f109080765fee6635e6fcd48>::<lambda_invoker_cdecl>(_T1,_T2 &&)': symbol cannot be defined within namespace 'Belle'

=> Compiler Error C2888
'identifier' : symbol cannot be defined within namespace 'namespace'
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2888?view=vs-2017

**Comment by WolfgangVogl** [comment]
See pull Request #3

**Comment by octobanana** [comment]
Hey, thank you for taking an interest in this project! I'll go take a look at your pull requests.

**Comment by octobanana** [comment]
After adding the _MSC_VER check, did it end up compiling alright?

**Comment by WolfgangVogl** [comment]
yes, sorry for the mass of pull requests - removed the old fork and made a new one

**Comment by WolfgangVogl** [comment]
New Pull Request ist #5

**Comment by octobanana** [comment]
fixed in bc7b6450f15181ec848ed35ba11ac5b2cf2f1ae5
